import type { Metadata } from "next";
import { Inter, Iceland, Dosis } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar/NavBar";
import ParticleBackground from "@/components/ParticleBackground";

const inter = Inter({ subsets: ["latin"] });
export const dosis = Dosis({ subsets: ["latin"], weight: ["200", "300", "400", "500", "600", "700", "800"] });
export const iceland = Iceland({ weight: "400", subsets: ["latin"], style: "normal" });

export const metadata: Metadata = {
  title: "🛸 AsterBizz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${dosis.className} bg-gradient-radial from-purple-700 to-purple-950 relative`}>
        <ParticleBackground />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
